<a href="https://colab.research.google.com/github/HayaKornblau/GitRepoExercise/blob/master/Ex1_Introduction_to_NumPy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #1: Introduction to NumPy arrays
In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

##Let’s create arrays in different ways:

First, you should import numpy as np

In [3]:
import numpy as np



### 1.   Read “Other ways to create arrays” on page 7-8 and then:




>(a) Create an array of zeros of shape (2,3,4) :







In [4]:
# Use np.zeros to create a (2,3,4) zero array
# Your Code Here#
a = np.zeros((2,3,4), dtype=int)

print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


 >(b) Create an array of ones of shape (2,3,4) :


In [5]:
# Use np.ones to create a (2,3,4) ones array
# Your Code Here#
b = np.ones((2,3,4), dtype=int)

print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


>(c) Create an array with values 0 to 999 using  np.arange  function.

In [6]:
# Your Code Here#
c = np.arange(stop=1000)
print(c)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

>(d) Create a 2-D array from the list [[1, 2.1, 3.2], [4, 5.4, 6.5]]:


In [7]:
# Try to define the list first and only after that convert it into an array
# Your Code Here#
dList = [[1, 2.1, 3.2], [4, 5.4, 6.5]]
d = np.array(dList)

print(d)

[[1.  2.1 3.2]
 [4.  5.4 6.5]]


>(e) Create a new array of zeros with the same dimensions and type of "d".

In [27]:
# Your Code Here#
e = (d-d).astype(int)

print(e)

[[0 0 0]
 [0 0 0]]


>(f) Create a new array of ones with the same dimensions and type of "d".

In [14]:
f = (d / d).astype(int)

print(f)

[[1 1 1]
 [1 1 1]]


### 2.  Let’s look at indexing and slicing arrays.

Read page 3-4 (without the final section describing the "reshape") and then:


>(a) Create an array from the list [2, 3.4, 5.5, -6.4, -2.2, 2.4]:

In [28]:
# Your code here:
a2List = [2, 3.4, 5.5, -6.4, -2.2, 2.4]
a2 = np.array(a2List)

print(a2)

[ 2.   3.4  5.5 -6.4 -2.2  2.4]


>(b) Do you know what a[1] will equal? Print it to see.


In [24]:
# Your code here:
print(a2[1])


3.4


>(c) Try printing a[1:4] to see what that equals.

In [29]:
# Your code here:
print(a2[1:4])


[ 3.4  5.5 -6.4]


>(d) Write a statement testing if "a2" contains the value 10.

In [23]:
# Your code here:
print(10 in a2)


False


>(e) Create a 2-D array from the following list and assign it to the variable "b2".
	[[2, 3.2, 5.5, -6.4, -2.2, 2.4],
	 [1, 22, 4, 0.1, 5.3, -9],
	 [3, 1, 2.1, 21, 1.1, -2]]


In [30]:
# Your code here:
b2List = [[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]
b2 = np.array(b2List)

print(b2)

[[ 2.   3.2  5.5 -6.4 -2.2  2.4]
 [ 1.  22.   4.   0.1  5.3 -9. ]
 [ 3.   1.   2.1 21.   1.1 -2. ]]


>(f) Can you guess what the following slices are equal to? Print them to check your understanding.
		b2[:, 3]
		b2[1:4, 0:4]
		b2[1:, 2]


In [26]:
# Your code here:
print(b2[:, 3])
print(b2[1:4, 0:4])
print(b2[1:, 2])


[-6.4  0.1 21. ]
[[ 1.  22.   4.   0.1]
 [ 3.   1.   2.1 21. ]]
[4.  2.1]
