<a href="https://colab.research.google.com/github/HayaKornblau/GitRepoExercise/blob/master/Exercise_2_Interrogating_and_manipulating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #2: Interrogating and manipulating arrays

###Aim: Learn how to interrogate and manipulate NumPy arrays

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Intertogating the properties of an array
*   Manipulating arrays to change their properties.



In [9]:
import numpy as np



### 1.  Let’s interrogate an array to find out its characteristics.
Recall what you’ve read in Exercise #1, read page 11 and then:





>(a)  Create a 2-D array shape (2,4) containing two lists:
 (range(4), range(10, 14)) and assign it to the variable "arr") :







In [18]:
# Your Code Here#
arr = np.array([np.arange(4), np.arange(10, 14)])

print(arr)

[[ 0  1  2  3]
 [10 11 12 13]]


>(b) Print the shape of the array :


In [23]:
# Your Code Here#
print(arr.shape)

(2, 4)




>(c)  Print the size of the array:



In [24]:
# Your Code Here#
print(arr.size)

8




>(d)  Print the maximum and minimum of the array:



In [20]:
# Your Code Here#
print(arr.min())
print(arr.max())


0
13


###2. Let’s generate new arrays by modifying our array.
Read the last code chunk on page 4 and read on until page 7  
	(up to “Other ways to create arrays” you’ve already read). Then:





>(a)  Continue to use the array "arr" as defined above:






> (b) Re-shape array "arr" to (2, 2, 2) and print it:




In [26]:
# Your Code Here#
arr = arr.reshape(2,2,2)




>(c)  Print the array transposed:




In [27]:
# Your Code Here#
print(arr)


[[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]]




>(d)  Print the array flattened to a single dimension:




In [28]:
# Your Code Here#
arr = arr.flatten()




>(e)  Print the array converted to floats:




In [34]:
# Your Code Here#
arr = arr.astype(float)
print(arr)


[ 0.  1.  2.  3. 10. 11. 12. 13.]




>(f) Create a 2-D array shape (2, 4) containing two lists [0, 3.1, 2.2, 1.1] and [7, 4, 3.14, 11] and assign it to the variable "arr2":




In [21]:
# Your Code Here#
arr2= np.array([[0, 3.1, 2.2, 1.1], [7, 4, 3.14, 11]])

print(arr2)

[[ 0.    3.1   2.2   1.1 ]
 [ 7.    4.    3.14 11.  ]]




>(g) Use  concatenate  function to concatenate "arr" and "arr2":




In [36]:
# Your Code Here#
arr = arr.reshape(2,4)
arr_conc = np.concatenate((arr,arr2))

print(arr_conc)

[[ 0.    1.    2.    3.  ]
 [10.   11.   12.   13.  ]
 [ 0.    3.1   2.2   1.1 ]
 [ 7.    4.    3.14 11.  ]]



> (h) As you’ve read on page 7, you can use newaxis function to expand the shape of a 1-D array. In the case of multidimensional arrays you can use expand_dims function as shown here. Use expand_dims function and print "arr" array re-shaped to (2, 4, 1):




In [52]:
# Your Code Here#
arr = np.expand_dims(arr,axis=2)
print(arr.shape)
print(arr)


(2, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[10]
  [11]
  [12]
  [13]]]


**Note:** np.fromstring() only works for floats. If we want to use it with other types, the type must be given as an argument, e.g. np.fromstring(str, dtype=int)