<a href="https://colab.research.google.com/github/HayaKornblau/GitRepoExercise/blob/master/Exercise_3_Array_calculations_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #3: Array calculations and operations

###Aim: Use NumPy arrays in mathematical calculations

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Mathematical operations with arrays.
*   Mathematical operations mixing scalars and arrays.
*   Comparisons operators and Boolean operations on arrays.
*   Using the "where" method.
*   Mathematical operations on vectors.
*   Find coefficients and roots of polynomial.



First, import NumPy as np:







In [1]:
import numpy as np



### 1.  Let’s perform some array calculations.
**Read “Array mathematics” (pages 8-10) and then:**





> (a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a":








In [86]:
# Your Code Here#
a = np.array([np.arange(4), np.arange(10, 14)])

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


> (b) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "b" :


In [3]:
# Your Code Here#
b = np.array([np.arange(4), np.arange(10, 14)])

print(b)

[[ 0  1  2  3]
 [10 11 12 13]]



> (c) Multiply array "a" by "b" and view the results:




In [7]:
# Your Code Here#
print(a * b)


[[  0   1   4   9]
 [100 121 144 169]]


Do you understand how NumPy has used its broadcasting feature to do the calculation even though the arrays are different shapes?



> (d) Multiply array "b" by 100 and assign the result to the variable "b1":



In [9]:
# Your Code Here#
b1 = 100 * b

print(b1)

[[   0  100  200  300]
 [1000 1100 1200 1300]]




> (e) Multiply array "b" by 100.0 and assign the result to the variable "b2":



In [69]:
# Your Code Here#
b2 = 100.0 * b

print(b2)

[[   0.  100.  200.  300.]
 [1000. 1100. 1200. 1300.]]




>(f) Print b1 == b2:





In [14]:
# Your Code Here#
print(b1 == b2)

[[ True  True  True  True]
 [ True  True  True  True]]


Are they the same?



>(g) Why do they display differently? Interrogate the typecode of each array to find out why:



In [18]:
# Your Code Here#
print(b1.dtype)
print(b2.dtype)


int64
float64


###2. Let's perform some operations on array.
Read the last code chunk on page 4 and read on until page 7 includes 
	Read “Basic array operations” (pages 11-12) and then:





> (a) Continue to use arrays "a" defined above:






> (b) Print the sum, mean and the product of "a" in two different ways:




In [87]:
# Your Code Here#
print(a.sum())
print(a.mean())
print(a.var())
print(a.std())


52
6.5
26.25
5.123475382979799




>(c) Print the variance and the standard deviation of "a"in two different ways:




In [46]:
# Your Code Here#

# calc var - way 1
print(a.std())

# calc var - way 2
x = np.abs(a - a.mean())**2
std = np.sqrt(np.mean(x))
print(std)

5.123475382979799
5.123475382979799


###3. Let’s look at array comparisons.
Read “Comparisons operators and value testing” (pages 12-14). Then:





>(a)  Create an array of values 0 to 9 and assign it to the variable "arr":




In [47]:
# Your Code Here#
arr = np.arange(stop=10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]




>(b)  Print two different ways of expressing the condition where the array is less than 3:




In [52]:
# Your Code Here#
print(arr < 3)
print(np.where(arr < 3, True, False))


[ True  True  True False False False False False False False]
[ True  True  True False False False False False False False]




>(c)  Create a numpy condition where "arr" is less than 3 OR greater than 8:




In [60]:
# Your Code Here#
print(arr[np.logical_or(arr < 3, arr > 8)])


[0 1 2 9]




>(d)  Use the  *where*  function to create a new array where the value is arr * 5 if the above condition is True and arr * -5 where the condition is False:




In [71]:
# Your Code Here#
arr1 = 5* np.where(np.logical_or(arr < 3, arr > 8), arr, -arr)
print(arr1)


[  0   5  10 -15 -20 -25 -30 -35 -40  45]


###4. Let’s look at item selection and manipulation.
Read “Array item selection and manipulation” (pages 14-16).






>(a)  Continue to use arrays "a" defined above:






>(b)  Print an array contains all the values from "a" that are greater than 1:




In [88]:
# Your Code Here#
print(a[a > 1])


[ 2  3 10 11 12 13]




>(c)  Print an array contains all the values from "a" that are greater than 3 and smaller than 11:




In [89]:
# Your Code Here#
print(a[np.logical_and(a > 3, a < 11)])


[10]




>(d)  Create an array from the list range(6) and assign it to the variable "b":



In [78]:
# Your Code Here#
b = np.array([np.arange(6)])
print(b)


[[0 1 2 3 4 5]]




>(e)  Use the  *put*  function to replace the first element of "b" with 6:




In [82]:
# Your Code Here#
b.put(5, 6)
print(b)


[[0 1 2 3 4 6]]




>(f)  Create an array from the list range(5) and assign it to the variable "c":




In [90]:
# Your Code Here#
c = np.array([np.arange(5)])
print(c)


[[0 1 2 3 4]]




>(g)   Use the  *put*  function to replace the first element of "b" with the last element of "c":



In [92]:
# Your Code Here#
b.put(0, a[-1])
print(b)


[[10  1  2  3  4  6]]


## Goog Job!!