<a href="https://colab.research.google.com/github/HayaKornblau/GitRepoExercise/blob/master/Exercise_4_Statistics_and_random_sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercise #4: Statistics and random sampling

###Aim: Use NumPy arrays in statistics and randomize samples

In this exercise we refers to a useful guide that can help you solve any questions in NumPy. This guide also summarize all that is needed to know about NumPy. [link to the guide](https://drive.google.com/file/d/0B9crmgoWupXkLTh0TS1HMzlrSVk/view)

###Issue covered:



*   Find the median of an array.
*   Find the correlation coefficient of an array.

*   Generate random sample from normal distribution.
*   Reordering array elements.


### First, import Numpy as np:




In [1]:
import numpy as np



### 1. Let’s look at array statistics.
Read “Statistics” on page 19 and then:





>(a) Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "a" :







In [2]:
# Your Code Here#
a = np.array([np.arange(4), np.arange(10, 14)])

print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


>(b) Print the median of "a" :


In [4]:
# Your Code Here#
print(np.median(a))

6.5




>(c)   Print the correlation coefficient of "a":



In [5]:
# Your Code Here#
print(np.corrcoef(a))

[[1. 1.]
 [1. 1.]]


###2. Let's generate random samples.
Read “Random numbers” (pages 19-21) and then:





>(a)  Create a random array of shape (2, 4):




In [6]:
# Your Code Here#
print(np.random.rand(2,4))


[[0.68055463 0.12032668 0.25999275 0.12455651]
 [0.82406279 0.09784624 0.59833317 0.72634596]]




>(b)  Use a function that selects a random integer between 2 to 10:




In [8]:
# Your Code Here#
print(np.random.randint(2,10))

7




>(c)  Generate a sample of size 40 from a standard normal distribution (with mean 0 and standard deviation 1), and assign it to the variable "b":




In [9]:
# Your Code Here#
b = np.random.normal(size=40)
print(b)

[-1.07623892e+00 -1.31781202e+00 -2.08258655e-01  1.25764556e+00
  7.24320560e-01  6.02906351e-01  8.20742813e-01 -5.92900208e-01
  2.00119682e-01 -5.45655866e-01  3.91061077e-01  1.07707300e+00
  1.95007487e+00  2.07681520e+00 -9.18454467e-01 -4.15222739e-01
 -1.59826047e+00 -8.70693288e-04  3.91565701e-01  1.13992551e-01
  8.85751572e-02  1.60331455e+00 -3.11143407e-01 -6.97542349e-01
  7.06109660e-01 -1.71154340e+00  1.20718633e+00  6.50480157e-01
  7.38267674e-01  2.63044981e-01 -1.65405743e-01 -9.15036289e-01
  1.92789375e-01 -5.35580228e-02  1.15490834e-01  2.86438260e-02
 -9.90103716e-01  1.21306217e+00  1.99190420e+00  9.56994292e-01]




>(d) Randomly shuffle the elements in "b", and print "b":




In [11]:
# Your Code Here#
np.random.shuffle(b)
print(b)


[ 3.91565701e-01 -8.70693288e-04  1.07707300e+00 -1.65405743e-01
  1.15490834e-01  2.86438260e-02  2.07681520e+00 -1.07623892e+00
  2.63044981e-01  1.20718633e+00 -9.90103716e-01  1.99190420e+00
  1.13992551e-01  1.25764556e+00 -5.45655866e-01  1.21306217e+00
  8.85751572e-02 -9.15036289e-01 -3.11143407e-01  7.38267674e-01
  7.06109660e-01 -4.15222739e-01  1.60331455e+00 -5.92900208e-01
  7.24320560e-01  1.95007487e+00  1.92789375e-01  2.00119682e-01
 -6.97542349e-01 -1.59826047e+00  9.56994292e-01  3.91061077e-01
  6.50480157e-01  6.02906351e-01 -1.71154340e+00 -1.31781202e+00
 -5.35580228e-02 -9.18454467e-01 -2.08258655e-01  8.20742813e-01]
